name = "zahra"
main = "src/worker.ts"
compatibility_date = "2024-05-29"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "settings", id = "a2ab1d39-fce5-47d0-8bb5-706e22300012" }
]
